export const actionTypes = {
  SET_USER_DATA: 'SET_USER_DATA',
  SET_USER_ROLE: 'SET_USER_ROLE',
  SET_NOTIFICATION: 'SET_NOTIFICATION',
  SET_LOADING: 'SET_LOADING',
  SET_FORMS: 'SET_FORMS',
  SET_FORM_DATA: 'SET_FORM_DATA',
};
